version: '3'

services:
  adminer:
    image: adminer:4.8.1
    container_name: light_control_adminer
    restart: always
    volumes:
      - ./volumes/adminer:/var/www/html/plugins-enabled
      - ./$DBMS_PATH:$DBMS_ACCESS_PATH
    environment:
      DBMS_ADMINER_PASSWORD: $DBMS_ADMINER_PASSWORD
      ADMINER_DESIGN: pepa-linha
    ports:
      - $ADMINER_PORT:8080

  light_control:
    image: light_control
    container_name: light_control
    restart: always
    build: .
    volumes:
      - ./$DBMS_PATH:/service/$DBMS_PATH
      - ./$LOG_FILE_PATH:/service/$LOG_FILE_PATH
    ports:
      - $LIGHT_CONTROL_PORT:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
